#!/usr/bin/env python3
"""Validate planning artifacts generated by embedded-feature-planner."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Iterable


PLAN_HEADINGS = (
    "# 方案：",
    "## 目标与范围",
    "## 现状与证据",
    "## 实现方案",
    "## 接口与影响面",
    "## 风险与待确认",
    "## 验收标准",
)

TODO_HEADINGS = (
    "# Todo：",
    "## 里程碑",
    "## 任务列表",
    "## 验收与回归",
    "## 风险跟踪",
)

DEBUG_REQUIRED_KEYS = (
    "feature",
    "created_at",
    "mode",
    "requirement",
    "evidence",
    "decisions",
    "debug_log",
    "status",
)


def require_headings(text: str, headings: Iterable[str], label: str) -> list[str]:
    errors: list[str] = []
    for heading in headings:
        if heading not in text:
            errors.append(f"{label} missing heading: {heading}")
    return errors


def validate_debug_json(data: dict) -> list[str]:
    errors: list[str] = []

    for key in DEBUG_REQUIRED_KEYS:
        if key not in data:
            errors.append(f"debug.json missing key: {key}")

    if not isinstance(data.get("requirement"), dict):
        errors.append("debug.json requirement must be an object")
    else:
        requirement = data["requirement"]
        if "input" not in requirement:
            errors.append("debug.json requirement.input is required")
        if "clarifications" not in requirement:
            errors.append("debug.json requirement.clarifications is required")

    for key in ("evidence", "decisions", "debug_log"):
        if key in data and not isinstance(data[key], list):
            errors.append(f"debug.json {key} must be a list")

    if isinstance(data.get("debug_log"), list):
        for index, item in enumerate(data["debug_log"], start=1):
            if not isinstance(item, dict):
                errors.append(f"debug.json debug_log[{index}] must be an object")
                continue
            for key in ("timestamp", "module", "issue", "fix", "result"):
                if key not in item:
                    errors.append(f"debug.json debug_log[{index}] missing key: {key}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", default=".", help="Workspace root to validate")
    args = parser.parse_args()

    workspace = Path(args.workspace).resolve()
    plan_path = workspace / "方案.md"
    todo_path = workspace / "Todo.md"
    debug_path = workspace / "debug.json"

    errors: list[str] = []

    if not plan_path.exists():
        errors.append("Missing file: 方案.md")
    else:
        plan_text = plan_path.read_text(encoding="utf-8")
        errors.extend(require_headings(plan_text, PLAN_HEADINGS, "方案.md"))

    if not todo_path.exists():
        errors.append("Missing file: Todo.md")
    else:
        todo_text = todo_path.read_text(encoding="utf-8")
        errors.extend(require_headings(todo_text, TODO_HEADINGS, "Todo.md"))

    if not debug_path.exists():
        errors.append("Missing file: debug.json")
    else:
        try:
            debug_data = json.loads(debug_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            errors.append(f"debug.json is not valid JSON: {exc}")
        else:
            errors.extend(validate_debug_json(debug_data))

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    print("Planning artifacts validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
