#!/usr/bin/env python3
"""Validate prompt output generated by expert-prompt-generator."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


PROMPT_PREFIXES = (
    ("你是", "You are"),
    ("任务：", "Task:"),
    ("约束：", "Constraints:"),
    ("输出：", "Output:"),
)


def split_prompt_lines(text: str) -> list[str]:
    return [line.strip() for line in text.splitlines() if line.strip()]


def validate_prompt_lines(lines: list[str]) -> list[str]:
    errors: list[str] = []
    if len(lines) != 4:
        errors.append(f"Prompt must contain exactly 4 non-empty lines, got {len(lines)}")
        return errors

    for index, prefixes in enumerate(PROMPT_PREFIXES):
        line = lines[index]
        if not any(line.startswith(prefix) for prefix in prefixes):
            expected = " / ".join(prefixes)
            errors.append(f"Line {index + 1} must start with {expected}")

    if "AI 助手" in lines[0] or "AI assistant" in lines[0]:
        errors.append("Role line is too generic")

    return errors


def extract_latest_prompt(describe_text: str) -> str | None:
    pattern = re.compile(
        r"\*\*生成 Prompt\*\*：\s*```(?:\r?\n)(.*?)(?:\r?\n)```",
        re.DOTALL,
    )
    matches = pattern.findall(describe_text)
    return matches[-1] if matches else None


def validate_describe_file(text: str) -> list[str]:
    errors: list[str] = []

    if "# Prompt 库" not in text:
        errors.append("describe_prompt.md missing file header")
    if "**原始需求**：" not in text:
        errors.append("describe_prompt.md missing 原始需求 block")
    if "**模式**：" not in text:
        errors.append("describe_prompt.md missing 模式 block")
    if "**生成 Prompt**：" not in text:
        errors.append("describe_prompt.md missing 生成 Prompt block")

    latest_prompt = extract_latest_prompt(text)
    if latest_prompt is None:
        errors.append("describe_prompt.md missing prompt code block")
        return errors

    errors.extend(validate_prompt_lines(split_prompt_lines(latest_prompt)))
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt-file", help="Validate a standalone prompt file")
    parser.add_argument("--describe-file", help="Validate describe_prompt.md")
    args = parser.parse_args()

    if not args.prompt_file and not args.describe_file:
        parser.error("Provide --prompt-file or --describe-file")

    errors: list[str] = []

    if args.prompt_file:
        prompt_path = Path(args.prompt_file).resolve()
        prompt_text = prompt_path.read_text(encoding="utf-8")
        errors.extend(validate_prompt_lines(split_prompt_lines(prompt_text)))

    if args.describe_file:
        describe_path = Path(args.describe_file).resolve()
        describe_text = describe_path.read_text(encoding="utf-8")
        errors.extend(validate_describe_file(describe_text))

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    print("Prompt validation passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
